### ISSUE TITLE
모임내에서 Github 어떻게 하면 잘 사용할 수 있을까요?

### ISSUE THREAD

**Issue by redongjun** [deliberate-practice/algo#1]
- 각자 공부한 것을 정리 및 공유
- 코드 리뷰

**Comment by maczniak** [comment]
* 책 내용 요약
* 풀이 과정과 주의할 부분
* (선택적) 자신의 풀이 업로드
* 미팅 후기

같은 organization member라도 저장소 push와 위키 편집 권한이 없습니다. [여기](https://help.github.com/articles/repository-permission-levels-for-an-organization/)에 보이는 Read/Write Permission조차 자동으로 주어지지 않는 것 같습니다.

**Comment by redongjun** [comment]
**책 내용 요약**은 WIKI로 하는 것이 좋을 지, README.md나 각 장별 문서를 만드는 것이 좋을 지 같이 고민해보면 좋을 것같습니다.  

**미팅 후기**는 회고 ([뒤돌아보다](http://agile.egloos.com/4122099))를 하였으면 좋겠는데, 개인적으로 이전까지 하였던 회고는 대부분 형식적이였습니다. 이번에는 [좋은 회고를 가려내는 법](http://agile.egloos.com/5829827)를 참고하여 성장하는 경험이 되기를 기대합니다. 

그리고 **풀이 과정**도 저번 모임을 통해 정말 중요하다는 것을 알게 되었습니다. 특히 TDD를 통해  사고의 흐름을 인지할 수 있고 한 걸음 쉬어가면서 더 깊이 사고 할 수 있는 것같습니다. - 다음 모임에 요즘 보고 있는 [임베디드 C를 위한 TDD](http://www.insightbook.co.kr/books/programming-insight/%EC%9E%84%EB%B2%A0%EB%94%94%EB%93%9C-c%EB%A5%BC-%EC%9C%84%ED%95%9C-tdd)를 소개드리겠습니다.

P.S. 두 분다 Owner로 변경하였습니다.
